/**
 * Dark Modern — a VS Code colour theme as a SystemSketch palette.
 *
 * GENERATED by scripts/import_vscode_theme.mjs — do not edit by hand.
 *
 * Read from, outermost first (each file overrides the one it includes):
 *   ../../../../../../usr/share/cursor/resources/app/extensions/theme-defaults/themes/dark_modern.json (sha256 e6a39ef275a3)
 *   ../../../../../../usr/share/cursor/resources/app/extensions/theme-defaults/themes/dark_plus.json (sha256 88f5b662378c)
 *   ../../../../../../usr/share/cursor/resources/app/extensions/theme-defaults/themes/dark_vs.json (sha256 d1b5e8ff4101)
 * Colours in the merged table: 139.
 * Tokens no layer named, painted from VS Code's defaults: surfaceHover, surfaceActive, warning, shadow1.
 */
import type { ThemePalette } from '../themeModel'

export const DARK_MODERN_PALETTE: ThemePalette = {
  id: "dark-modern",
  label: "Dark Modern",
  scheme: "dark",
  source: "VS Code · Default Dark Modern",
  tokens: {
    surface: "#1f1f1f",
    surfaceRaised: "#202020",
    surfaceSunken: "#313131",
    surfaceHover: "#5a5d5e50",
    surfaceActive: "#63666750",
    surfaceInverse: "color-mix(in srgb, #202020 86%, #cccccc)",
    text: "#cccccc",
    textMuted: "#9d9d9d",
    textFaint: "#989898",
    textInverse: "#cccccc",
    border: "#313131",
    accent: "#0078d4",
    accentText: "#ffffff",
    danger: "#f85149",
    warning: "#cca700",
    success: "#2ea043",
    codeSurface: "#1f1f1f",
    codeText: "#cccccc",
    shadow1: "0 1px 3px #0000005c",
    shadow2: "0 4px 14px #0000005c",
  },
}
