/**
 * Obsidian's default theme as two SystemSketch palettes.
 *
 * GENERATED by scripts/extract_obsidian_palette.py — do not edit by hand.
 *
 * Read from Obsidian 1.13.7 (/home/bam/.config/obsidian/obsidian-1.13.7.asar), app.css sha256 f612f1e8f364.
 * Each variable is the one the [data-ss-theme='obsidian'] host block in
 * tokens.css reads, resolved through Obsidian's own cascade to a literal, so
 * a board looks the same hosted in Obsidian and merely wearing its look.
 */
import type { ThemePalette } from '../themeModel'

export const OBSIDIAN_LIGHT_PALETTE: ThemePalette = {
  id: 'obsidian-light',
  label: 'Obsidian Light',
  scheme: 'light',
  source: 'Obsidian 1.13.7 default theme',
  tokens: {
    // --background-primary: --background-primary = var(--color-base-00) ← --color-base-00 = #ffffff
    surface: "#ffffff",
    // --background-secondary: --background-secondary = var(--color-base-20) ← --color-base-20 = #f6f6f6
    surfaceRaised: "#f6f6f6",
    // --background-modifier-form-field: --background-modifier-form-field = var(--color-base-00) ← --color-base-00 = #ffffff
    surfaceSunken: "#ffffff",
    // --background-modifier-hover: --background-modifier-hover = color-mix(in oklch, var(--mono-100) 6.7%, transparent) ← --mono-100 = black
    surfaceHover: "rgb(0 0 0 / 6.7%)",
    // --background-modifier-active-hover: --background-modifier-active-hover = color-mix(in oklch, var(--interactive-accent) 10%, transparent) ← --interactive-accent = var(--color-accent-1) ← --color-accent-1 = hsl(calc(var(--accent-h) - 1), calc(var(--accent-s) * 1.01), calc(var(--accent-l) * 1.075)) ← --accent-h = 258 ← --accent-s = 88% ← --accent-l = 66%
    surfaceActive: "rgb(152 115 247 / 10%)",
    // --background-modifier-message: --background-modifier-message = color-mix(in oklch, black 90%, transparent)
    surfaceInverse: "rgb(0 0 0 / 90%)",
    // --text-normal: --text-normal = var(--color-base-100) ← --color-base-100 = #222222
    text: "#222222",
    // --text-muted: --text-muted = var(--color-base-70) ← --color-base-70 = #5c5c5c
    textMuted: "#5c5c5c",
    // --text-faint: --text-faint = var(--color-base-50) ← --color-base-50 = #ababab
    textFaint: "#ababab",
    // --text-on-accent: --text-on-accent = white
    textInverse: "white",
    // --background-modifier-border: --background-modifier-border = var(--color-base-30) ← --color-base-30 = #e4e4e4
    border: "#e4e4e4",
    // --interactive-accent: --interactive-accent = var(--color-accent-1) ← --color-accent-1 = hsl(calc(var(--accent-h) - 1), calc(var(--accent-s) * 1.01), calc(var(--accent-l) * 1.075)) ← --accent-h = 258 ← --accent-s = 88% ← --accent-l = 66%
    accent: "#9873f7",
    // --text-on-accent: --text-on-accent = white
    accentText: "white",
    // --text-error: --text-error = var(--color-red) ← --color-red = #e93147
    danger: "#e93147",
    // --text-warning: --text-warning = var(--color-orange) ← --color-orange = #ec7500
    warning: "#ec7500",
    // --color-green: --color-green = #08b94e
    success: "#08b94e",
    // --code-background: --code-background = var(--background-primary-alt) ← --background-primary-alt = var(--color-base-10) ← --color-base-10 = #fafafa
    codeSurface: "#fafafa",
    // --code-normal: --code-normal = var(--text-normal) ← --text-normal = var(--color-base-100) ← --color-base-100 = #222222
    codeText: "#222222",
    // --shadow-s: --shadow-s = 0px 1px 2px rgba(0, 0, 0, 0.028), 0px 3.4px 6.7px rgba(0, 0, 0, 0.042), 0px 15px 30px rgba(0, 0, 0, 0.07)
    shadow1: "0px 1px 2px rgba(0, 0, 0, 0.028), 0px 3.4px 6.7px rgba(0, 0, 0, 0.042), 0px 15px 30px rgba(0, 0, 0, 0.07)",
    // --shadow-l: --shadow-l = 0px 1.8px 7.3px rgba(0, 0, 0, 0.071), 0px 6.3px 24.7px rgba(0, 0, 0, 0.112), 0px 15px 30px rgba(0, 0, 0, 0.1)
    shadow2: "0px 1.8px 7.3px rgba(0, 0, 0, 0.071), 0px 6.3px 24.7px rgba(0, 0, 0, 0.112), 0px 15px 30px rgba(0, 0, 0, 0.1)",
  },
}

export const OBSIDIAN_DARK_PALETTE: ThemePalette = {
  id: 'obsidian-dark',
  label: 'Obsidian Dark',
  scheme: 'dark',
  source: 'Obsidian 1.13.7 default theme',
  tokens: {
    // --background-primary: --background-primary = var(--color-base-00) ← --color-base-00 = #1C1C1C
    surface: "#1C1C1C",
    // --background-secondary: --background-secondary = var(--color-base-20) ← --color-base-20 = #282828
    surfaceRaised: "#282828",
    // --background-modifier-form-field: --background-modifier-form-field = var(--color-base-25) ← --color-base-25 = #2e2e2e
    surfaceSunken: "#2e2e2e",
    // --background-modifier-hover: --background-modifier-hover = color-mix(in oklch, var(--mono-100) 6.7%, transparent) ← --mono-100 = white
    surfaceHover: "rgb(255 255 255 / 6.7%)",
    // --background-modifier-active-hover: --background-modifier-active-hover = color-mix(in oklch, var(--interactive-accent) 10%, transparent) ← --interactive-accent = var(--color-accent) ← --color-accent = hsl(var(--accent-h), var(--accent-s), var(--accent-l)) ← --accent-h = 258 ← --accent-s = 88% ← --accent-l = 66%
    surfaceActive: "rgb(138 92 245 / 10%)",
    // --background-modifier-message: --background-modifier-message = color-mix(in oklch, black 90%, transparent)
    surfaceInverse: "rgb(0 0 0 / 90%)",
    // --text-normal: --text-normal = var(--color-base-100) ← --color-base-100 = #dadada
    text: "#dadada",
    // --text-muted: --text-muted = var(--color-base-70) ← --color-base-70 = #b3b3b3
    textMuted: "#b3b3b3",
    // --text-faint: --text-faint = var(--color-base-50) ← --color-base-50 = #666666
    textFaint: "#666666",
    // --text-on-accent: --text-on-accent = white
    textInverse: "white",
    // --background-modifier-border: --background-modifier-border = var(--color-base-30) ← --color-base-30 = #333333
    border: "#333333",
    // --interactive-accent: --interactive-accent = var(--color-accent) ← --color-accent = hsl(var(--accent-h), var(--accent-s), var(--accent-l)) ← --accent-h = 258 ← --accent-s = 88% ← --accent-l = 66%
    accent: "#8a5cf5",
    // --text-on-accent: --text-on-accent = white
    accentText: "white",
    // --text-error: --text-error = var(--color-red) ← --color-red = #fb464c
    danger: "#fb464c",
    // --text-warning: --text-warning = var(--color-orange) ← --color-orange = #e9973f
    warning: "#e9973f",
    // --color-green: --color-green = #44cf6e
    success: "#44cf6e",
    // --code-background: --code-background = var(--background-primary-alt) ← --background-primary-alt = var(--color-base-10) ← --color-base-10 = #232323
    codeSurface: "#232323",
    // --code-normal: --code-normal = var(--text-normal) ← --text-normal = var(--color-base-100) ← --color-base-100 = #dadada
    codeText: "#dadada",
    // --shadow-s: --shadow-s = 0px 1px 2px rgba(0, 0, 0, 0.121), 0px 3.4px 6.7px rgba(0, 0, 0, 0.179), 0px 15px 30px rgba(0, 0, 0, 0.3)
    shadow1: "0px 1px 2px rgba(0, 0, 0, 0.121), 0px 3.4px 6.7px rgba(0, 0, 0, 0.179), 0px 15px 30px rgba(0, 0, 0, 0.3)",
    // --shadow-l: --shadow-l = 0px 1.8px 7.3px rgba(0, 0, 0, 0.071), 0px 6.3px 24.7px rgba(0, 0, 0, 0.112), 0px 30px 90px rgba(0, 0, 0, 0.2)
    shadow2: "0px 1.8px 7.3px rgba(0, 0, 0, 0.071), 0px 6.3px 24.7px rgba(0, 0, 0, 0.112), 0px 30px 90px rgba(0, 0, 0, 0.2)",
  },
}
