/**
 * The whole Lucide library, loaded lazily for the picker and for any Block
 * whose icon is outside the curated static set.
 *
 * Data is `data/lucide-icons.json`, generated by `scripts/sync_icon_library.mjs`
 * from lucide-static at the same version as lucide-react (asserted by a test).
 * Rendering uses lucide's own default SVG attributes so a glyph drawn from this
 * JSON is pixel-identical to the same icon drawn by lucide-react.
 *
 * WHY one lazy JSON chunk and not `lucide-react/dynamic` — see docs/peps/0014-block-icon-asset-prop-and-one-lazy-lucide-chunk.md: DynamicIcon emits one
 * chunk per icon (1,800+ files in the build and the VSIX). One chunk loads once
 * per session, and only when a board or the picker needs it.
 */
import { createElement, type CSSProperties } from 'react'

export type LucideIconNode = ReadonlyArray<readonly [tag: string, attrs: Readonly<Record<string, string | number>>]>

export interface LucideLibraryEntry {
	/** lucide-react export name, the value stored in a Block's `icon` prop. */
	readonly name: string
	/** lucide's own kebab-case id, shown to people. */
	readonly kebab: string
	readonly tags: readonly string[]
	readonly node: LucideIconNode
}

export interface LucideLibrary {
	readonly version: string
	readonly entries: readonly LucideLibraryEntry[]
	readonly byName: ReadonlyMap<string, LucideLibraryEntry>
	search(query: string): LucideLibraryEntry[]
}

let loaded: LucideLibrary | null = null
let loading: Promise<LucideLibrary> | null = null
const listeners = new Set<() => void>()

/** Synchronous view: null until `loadLucideLibrary()` has resolved once. */
export function peekLucideLibrary(): LucideLibrary | null {
	return loaded
}

/** Notifies once the library becomes available; returns the unsubscribe. */
export function subscribeLucideLibrary(listener: () => void): () => void {
	listeners.add(listener)
	return () => {
		listeners.delete(listener)
	}
}

export function loadLucideLibrary(): Promise<LucideLibrary> {
	if (loaded) return Promise.resolve(loaded)
	if (!loading) {
		loading = import('./data/lucide-icons.json').then((module) => {
			const data = (module.default ?? module) as unknown as { version: string; icons: LucideLibraryEntry[] }
			loaded = buildLucideLibrary(data.version, data.icons)
			for (const listener of listeners) listener()
			return loaded
		})
	}
	return loading
}

export function buildLucideLibrary(version: string, entries: readonly LucideLibraryEntry[]): LucideLibrary {
	const byName = new Map(entries.map((entry) => [entry.name, entry]))
	return {
		version,
		entries,
		byName,
		search: (query) => searchLucide(entries, query),
	}
}

/**
 * Notion-style filter: every typed word must match the icon's id or one of its
 * tags. Ranked id-exact › id-prefix › tag-exact › id-contains › tag-prefix ›
 * tag-contains, then alphabetical. No fuzzing — Notion doesn't fuzz either.
 */
export function searchLucide(entries: readonly LucideLibraryEntry[], query: string): LucideLibraryEntry[] {
	const terms = query.toLowerCase().split(/\s+/).filter(Boolean)
	if (terms.length === 0) return [...entries]
	const scored: Array<[number, LucideLibraryEntry]> = []
	for (const entry of entries) {
		let score = 0
		for (const term of terms) {
			let best = 0
			if (entry.kebab === term) best = 100
			else if (entry.kebab.startsWith(term)) best = 60
			else if (entry.kebab.includes(term)) best = 40
			for (const tag of entry.tags) {
				if (tag === term) best = Math.max(best, 50)
				else if (tag.startsWith(term)) best = Math.max(best, 30)
				else if (tag.includes(term)) best = Math.max(best, 15)
			}
			if (best === 0) {
				score = 0
				break
			}
			score += best
		}
		if (score > 0) scored.push([score, entry])
	}
	scored.sort((a, b) => b[0] - a[0] || a[1].kebab.localeCompare(b[1].kebab))
	return scored.map(([, entry]) => entry)
}

/** Renders a Lucide node with lucide-react's default attributes. */
export function LucideNodeSvg({
	node,
	size,
	className,
	style,
}: {
	node: LucideIconNode
	size: number
	className?: string
	style?: CSSProperties
}) {
	return createElement(
		'svg',
		{
			xmlns: 'http://www.w3.org/2000/svg',
			width: size,
			height: size,
			viewBox: '0 0 24 24',
			fill: 'none',
			stroke: 'currentColor',
			strokeWidth: 2,
			strokeLinecap: 'round',
			strokeLinejoin: 'round',
			className,
			style,
			'aria-hidden': 'true',
		},
		...node.map(([tag, attrs], index) => createElement(tag, { ...attrs, key: index })),
	)
}
