#!/usr/bin/env node
/**
 * Read a VS Code / Cursor colour theme into a shipped SystemSketch palette.
 *
 *   node --experimental-strip-types scripts/import_vscode_theme.mjs \
 *     /usr/share/cursor/resources/app/extensions/theme-defaults/themes/dark_modern.json \
 *     --id dark-modern --label "Dark Modern" --export DARK_MODERN_PALETTE \
 *     --out src/theme/palettes/darkModern.ts
 *
 * VS Code's built-in themes are layered: `dark_modern.json` includes
 * `dark_plus.json`, which includes `dark_vs.json`, and a colour is whichever
 * layer named it last. This resolves that chain the way VS Code does, then
 * hands the merged table to the same `vsCodeThemeTokens` the Settings dialog
 * uses on an imported file — one mapping, two callers.
 *
 * The emitted module records where every value came from: the file, its
 * sha256, the include chain, and which tokens fell back to a VS Code default
 * because no layer named them.
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  parseVsCodeThemeText,
  vsCodeThemeScheme,
  vsCodeThemeTokens,
} from '../src/theme/vscodeTheme.ts'
import { TOKEN_NAMES } from '../src/theme/themeModel.ts'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))

function argument(name, fallback) {
  const index = process.argv.indexOf(`--${name}`)
  return index >= 0 ? process.argv[index + 1] : fallback
}

const themePath = process.argv[2]
if (!themePath || themePath.startsWith('--')) {
  console.error('usage: import_vscode_theme.mjs <theme.json> --id <id> --label <label> --export <NAME> --out <file.ts>')
  process.exit(2)
}

/** The include chain, outermost first, each with its file's own colours. */
function layers(path, seen = new Set()) {
  const absolute = resolve(path)
  if (seen.has(absolute)) throw new Error(`include cycle at ${absolute}`)
  seen.add(absolute)
  const text = readFileSync(absolute, 'utf8')
  const theme = parseVsCodeThemeText(text)
  const layer = {
    path: absolute,
    sha256: createHash('sha256').update(text).digest('hex'),
    theme,
  }
  const parents = theme.include ? layers(resolve(dirname(absolute), theme.include), seen) : []
  return [layer, ...parents]
}

const chain = layers(themePath)
const [outermost] = chain
// Deepest include first, so the outermost file overrides.
const colors = {}
for (const layer of [...chain].reverse()) Object.assign(colors, layer.theme.colors ?? {})
const merged = { ...outermost.theme, colors }

const id = argument('id', 'imported')
const label = argument('label', outermost.theme.name ?? id)
const exportName = argument('export', 'IMPORTED_PALETTE')
const out = resolve(ROOT, argument('out', `src/theme/palettes/${id}.ts`))
const scheme = vsCodeThemeScheme(merged)
const { tokens, fallbacks } = vsCodeThemeTokens(colors, scheme)

const source = `VS Code · ${outermost.theme.name ?? label}`
const describe = (path) => {
  const inRepo = relative(ROOT, path)
  return inRepo.startsWith('..') ? path : inRepo
}
const provenance = chain.map((layer) => `${describe(layer.path)} (sha256 ${layer.sha256.slice(0, 12)})`)

const lines = [
  '/**',
  ` * ${label} — a VS Code colour theme as a SystemSketch palette.`,
  ' *',
  ' * GENERATED by scripts/import_vscode_theme.mjs — do not edit by hand.',
  ' *',
  ' * Read from, outermost first (each file overrides the one it includes):',
  ...provenance.map((line) => ` *   ${line}`),
  ` * Colours in the merged table: ${Object.keys(colors).length}.`,
  fallbacks.length
    ? ` * Tokens no layer named, painted from VS Code's defaults: ${fallbacks.join(', ')}.`
    : ' * Every token was named by the theme itself; no VS Code default was needed.',
  ' */',
  "import type { ThemePalette } from '../themeModel'",
  '',
  `export const ${exportName}: ThemePalette = {`,
  `  id: ${JSON.stringify(id)},`,
  `  label: ${JSON.stringify(label)},`,
  `  scheme: ${JSON.stringify(scheme)},`,
  `  source: ${JSON.stringify(source)},`,
  '  tokens: {',
  ...TOKEN_NAMES.map((name) => `    ${name}: ${JSON.stringify(tokens[name])},`),
  '  },',
  '}',
  '',
]
writeFileSync(out, lines.join('\n'), 'utf8')
console.log(`wrote ${relative(ROOT, out)} (${scheme}, ${Object.keys(colors).length} colours, ${fallbacks.length} fallbacks${fallbacks.length ? `: ${fallbacks.join(', ')}` : ''})`)
