#!/usr/bin/env python3
"""Create an isolated worktree for one track, and prove it can serve itself.

    python3 scripts/new_track.py block-grid
    python3 scripts/new_track.py --list
    python3 scripts/new_track.py --remove block-grid

A worktree gives an agent its own files, index and HEAD. It does *not* give it
its own ports, its own release runtime, or its own board — all three default to
machine-global paths, so two agents sharing them will quietly fight over Zach's
running Preview and his real `~/SystemSketch/Untitled.tldr`. This script closes
those three gaps at creation time so a track agent never has to discover them.

Deliberately does not touch `package.json`: `npm run dev` is pinned to 4322 with
`--strictPort`, so the generated `serve.sh` invokes vite directly with the
track's own port instead. Nothing shared is edited.

Only the standard library is used.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Track 0 is Zach's own checkout on 4321/4322/4323. Tracks start above it, ten
# apart, so a track's ports are readable from its index alone.
FIRST_TRACK_PORT_BASE = 4330
PORT_STRIDE = 10


def run(*args: str, cwd: Path = REPO, check: bool = True) -> str:
    result = subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, check=False
    )
    if check and result.returncode != 0:
        raise SystemExit(f"$ {' '.join(args)}\n{result.stdout}{result.stderr}")
    return (result.stdout + result.stderr).strip()


def worktree_path(name: str) -> Path:
    return REPO.parent / f"systemsketch-track-{name}"


def existing_tracks() -> dict[str, Path]:
    """Every track worktree git currently knows about, by track name."""
    found: dict[str, Path] = {}
    for line in run("git", "worktree", "list", "--porcelain").splitlines():
        if line.startswith("worktree "):
            path = Path(line.split(" ", 1)[1])
            prefix = "systemsketch-track-"
            if path.name.startswith(prefix):
                found[path.name[len(prefix):]] = path
    return found


def next_free_index() -> int:
    """Lowest index whose whole port range is unclaimed by a live worktree."""
    taken = {index_of(path) for path in existing_tracks().values()}
    taken.discard(None)
    index = 1
    while index in taken:
        index += 1
    return index


def index_of(path: Path) -> int | None:
    marker = path / ".track" / "index"
    if marker.is_file():
        try:
            return int(marker.read_text().strip())
        except ValueError:
            return None
    return None


def ports_for(index: int) -> tuple[int, int]:
    base = FIRST_TRACK_PORT_BASE + (index - 1) * PORT_STRIDE
    return base, base + 1


def port_is_free(port: int) -> bool:
    import socket

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            probe.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


SERVE_TEMPLATE = """#!/usr/bin/env bash
# Serve THIS track, isolated from Zach's Stable/Preview and from his real board.
# Generated by scripts/new_track.py — edit the ports here, not in package.json.
set -euo pipefail
cd "$(dirname "$0")"

export SYSTEMSKETCH_RELEASE_HOME="$PWD/.track/runtime"
export SYSTEMSKETCH_STATE_HOME="$PWD/.track/state"

python3 scripts/server.py \\
  --port {api_port} \\
  --files-root "$PWD/.track/boards" \\
  --dist dist \\
  --channel preview \\
  --build track-{name} \\
  --source-root "$PWD" &
API_PID=$!
trap 'kill $API_PID 2>/dev/null || true' EXIT

SYSTEMSKETCH_API_PORT={api_port} \\
  npx vite --host 127.0.0.1 --port {dev_port} --strictPort
"""

TRACK_MD_TEMPLATE = """# Track: {name}

Worktree for one lane of SystemSketch. Branch `track/{name}`, forked from
`{base_ref}` at `{base_sha}`.

## Yours, and only yours

| | |
|---|---|
| dev server | **http://127.0.0.1:{dev_port}** |
| API | 127.0.0.1:{api_port} |
| release runtime | `.track/runtime/` |
| app state | `.track/state/` |
| boards | `.track/boards/` |

```bash
cd {path} && ./serve.sh
```

**Do not use `npm run dev`** — it is pinned to 4322 with `--strictPort`, which
is Zach's running Preview. `serve.sh` runs vite directly on your own port.

**Do not run `npm run release:candidate` or `release:promote` without
`SYSTEMSKETCH_RELEASE_HOME` set** — `serve.sh` exports it, but a bare shell does
not. The default release home is `~/.local/share/systemsketch/runtime`, which is
what Zach's Preview on 4322 serves. Publishing there replaces what he is looking
at.

**Never point a test at `~/SystemSketch/Untitled.tldr`.** That is his real board
and the app autosaves into it. `.track/boards/` is yours; the server above is
already rooted there.

## Before you hand anything back

```bash
cd {path} && npm run check
```

Then drive the change in a real browser — a `tests/*_smoke.mjs` CDP journey
against your own port — and look at the screenshots. `npm run check` is
necessary and not sufficient for UI work.

## Merging

Merge to `main` daily. Branch age, not isolation, is what turns parallel work
into a bad merge. `main` moves under you: other sessions are editing it right
now.
"""


def create(name: str, index: int | None, base: str) -> None:
    path = worktree_path(name)
    if path.exists():
        raise SystemExit(f"{path} already exists — pick another name, or --remove it")

    index = index if index is not None else next_free_index()
    dev_port, api_port = ports_for(index)
    for label, port in (("dev", dev_port), ("api", api_port)):
        if not port_is_free(port):
            raise SystemExit(
                f"track {index}'s {label} port {port} is already bound — "
                f"pass --index with a free slot"
            )

    base_sha = run("git", "rev-parse", "--short", base)
    branch = f"track/{name}"
    run("git", "worktree", "add", "-b", branch, str(path), base)

    track_dir = path / ".track"
    for sub in ("runtime", "state", "boards"):
        (track_dir / sub).mkdir(parents=True, exist_ok=True)
    (track_dir / "index").write_text(f"{index}\n", encoding="utf-8")

    # node_modules is 200 MB and `git worktree add` does not copy it. A symlink
    # is correct here: the dependency set is pinned by the lockfile both trees
    # share, so there is nothing to diverge.
    node_modules = path / "node_modules"
    if not node_modules.exists():
        node_modules.symlink_to(REPO / "node_modules")

    serve = path / "serve.sh"
    serve.write_text(
        SERVE_TEMPLATE.format(name=name, dev_port=dev_port, api_port=api_port),
        encoding="utf-8",
    )
    serve.chmod(0o755)

    (path / "TRACK.md").write_text(
        TRACK_MD_TEMPLATE.format(
            name=name,
            path=path,
            dev_port=dev_port,
            api_port=api_port,
            base_ref=base,
            base_sha=base_sha,
        ),
        encoding="utf-8",
    )

    # Keep the track's own scaffolding out of its diffs.
    exclude = path / ".git"
    info = (
        Path(exclude.read_text().split("gitdir:")[1].strip())
        if exclude.is_file()
        else exclude
    ) / "info"
    info.mkdir(parents=True, exist_ok=True)
    (info / "exclude").write_text(
        "\n".join(["", "# scripts/new_track.py scaffolding", ".track/", "serve.sh", "TRACK.md", ""]),
        encoding="utf-8",
    )

    print(f"track {index}: {name}")
    print(f"  worktree  {path}")
    print(f"  branch    {branch}  (from {base} {base_sha})")
    print(f"  serve     cd {path} && ./serve.sh")
    print(f"  open      http://127.0.0.1:{dev_port}")
    print(f"  brief     {path / 'TRACK.md'}")


def remove(name: str) -> None:
    path = worktree_path(name)
    if not path.exists():
        raise SystemExit(f"no worktree at {path}")
    # Drop the symlink first so nothing can descend into the real node_modules.
    node_modules = path / "node_modules"
    if node_modules.is_symlink():
        node_modules.unlink()
    run("git", "worktree", "remove", "--force", str(path))
    print(f"removed {path} (branch track/{name} kept — delete it yourself if it is merged)")


def show_list() -> None:
    tracks = existing_tracks()
    if not tracks:
        print("no track worktrees")
        return
    for name, path in sorted(tracks.items()):
        index = index_of(path)
        ports = f"{ports_for(index)[0]}/{ports_for(index)[1]}" if index else "?"
        live = "up" if index and not port_is_free(ports_for(index)[0]) else "down"
        print(f"  {name:<20} track {index}  ports {ports:<12} {live:<5} {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("name", nargs="?", help="track name, e.g. block-grid")
    parser.add_argument("--index", type=int, help="port slot (default: next free)")
    parser.add_argument("--base", default="main", help="ref to fork from (default: main)")
    parser.add_argument("--remove", metavar="NAME", help="remove a track worktree")
    parser.add_argument("--list", action="store_true", help="list track worktrees")
    args = parser.parse_args()

    if args.list:
        show_list()
    elif args.remove:
        remove(args.remove)
    elif args.name:
        create(args.name, args.index, args.base)
    else:
        parser.print_help()
        sys.exit(2)


if __name__ == "__main__":
    main()
