#!/usr/bin/env python3
"""Build the self-contained Frames-panel implementation gallery."""

from __future__ import annotations

import base64
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCREENSHOT = ROOT / "docs/assets/frames-panel-2026-09-04.png"
OUTPUT = ROOT / "docs/frames-panel-gallery-2026-09-04.html"


def main() -> None:
    image = "data:image/png;base64," + base64.b64encode(SCREENSHOT.read_bytes()).decode("ascii")
    OUTPUT.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Frames panel · SystemSketch implementation gallery</title><style>
:root{{--ink:#eff5ff;--muted:#acbbd0;--bg:#0c1320;--card:#151f30;--line:#32445d;--blue:#65a8ff;--mint:#69dcad;--amber:#ffbd5b}}*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at 8% 0,#1c3558,transparent 34%),var(--bg);color:var(--ink);font:15px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}}main{{max-width:1180px;margin:auto;padding:58px 26px 82px}}h1{{max-width:830px;margin:8px 0 16px;font-size:clamp(38px,6vw,66px);line-height:.98;letter-spacing:-.06em}}h2{{margin:0 0 10px;font-size:21px}}p{{color:var(--muted)}}.eyebrow{{color:var(--blue);font-size:11px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}}.lede{{max-width:780px;font-size:19px}}.hero,.card{{border:1px solid var(--line);border-radius:18px;background:color-mix(in srgb,var(--card) 94%,transparent)}}.hero{{overflow:hidden;margin-top:30px}}.hero img{{display:block;width:100%;height:auto}}.caption{{padding:16px 20px;border-top:1px solid var(--line);color:var(--muted)}}.grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:18px}}.card{{padding:22px}}.wide{{grid-column:1/-1}}.flow{{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:10px;align-items:stretch;text-align:center}}.node{{min-height:116px;padding:18px 14px;border:1px solid var(--line);border-radius:13px;background:#101a2a}}.node b{{display:block;margin-bottom:8px;font-size:16px}}.arrow{{align-self:center;color:var(--blue);font-size:27px;font-weight:850}}ul{{margin:0;padding-left:20px;color:var(--muted)}}li+li{{margin-top:8px}}code{{padding:2px 5px;border-radius:5px;background:#0a101a;color:#bfdbfe}}.good{{border-top:3px solid var(--mint)}}.safe{{border-top:3px solid var(--amber)}}a{{color:#9dcbff}}footer{{margin-top:32px;color:var(--muted);font-size:13px}}@media(max-width:760px){{.grid{{grid-template-columns:1fr}}.flow{{grid-template-columns:1fr}}.arrow{{transform:rotate(90deg)}}}}
</style></head><body><main><div class="eyebrow">Implementation gallery · 2026-09-04</div><h1>Frames, regions, and saved cameras now share one honest navigation surface.</h1><p class="lede">The right-side Frames panel is a compact working index, not a pretend slide deck: structural targets retain their own local previews, while saved views render the exact page-space viewport captured by their camera pose.</p>
<section class="hero"><img src="{image}" alt="The real SystemSketch app with the Frames panel open: Architecture and Runtime have local thumbnail cards while Architecture camera shows a distinct saved viewport"><div class="caption"><b>Real browser capture.</b> The landmark card’s visible content is the saved camera viewport, rather than a repeated whole-board thumbnail.</div></section>
<section class="grid"><article class="card good"><h2>One list, distinct meanings</h2><ul><li>Stock Frames, Branch regions, and expanded Blocks remain real canvas records.</li><li>A <code>⌖</code> icon distinguishes board-persisted saved cameras without splitting navigation into a second panel.</li><li>Each item focuses its real target; a saved camera restores only camera x/y/z and leaves selection intact.</li></ul></article><article class="card safe"><h2>Safe persistence</h2><ul><li>Order is a small versioned projection in page metadata; it never rewrites Frame records or landmark payloads.</li><li>Unknown, malformed, or duplicate order data is protected. Landmark metadata protection stays independent.</li><li>Single-page migration carries only readable shape order; collision-renamed camera ids fall back safely, and opaque source metadata remains preserved on its imported Frame.</li></ul></article><article class="card wide"><h2>Visible interaction path</h2><div class="flow"><div class="node"><b>Thumbnail cards</b>Preview local frame/region geometry or the saved camera viewport.</div><div class="arrow">→</div><div class="node"><b>Work directly</b>Switch to compact list, double-click a row to rename, or drag its grip above/below another.</div><div class="arrow">→</div><div class="node"><b>Persist safely</b>One duplicate-free ordering record survives ordinary board save/reopen.</div></div></article><article class="card"><h2>Real-browser proof</h2><ul><li>7/7 checks: previews, saved viewport, panel mode, direct rename, pointer reorder, focus, item menu, and console cleanliness.</li><li>The smoke captures this exact PNG from a disposable board and exercises a true browser drag sequence.</li><li>Focused model tests pin the measured camera projection <code>{{x:-410,y:-230,z:.72}}</code> → page viewport <code>{{410,230,1666.67,1111.11}}</code>.</li></ul></article><article class="card"><h2>Editing contract</h2><p>Outside double-click enters an in-place text field; Enter commits, Escape cancels. Structural labels retain native empty/default semantics and avoid no-op history entries. Saved-view names retain their stricter unique 1–80-character persistence contract, with visible errors.</p></article></section><footer>Evidence: <a href="../src/chrome/BoardOverview.tsx">panel</a> · <a href="../src/chrome/framesPanelModel.ts">model</a> · <a href="../tests/frames_panel_smoke.mjs">browser smoke</a> · <a href="../sketches/review/frames-panel.systemsketch">review board</a> · <a href="build_frames_panel_gallery.py">builder</a></footer></main></body></html>''', encoding="utf-8")
    print(OUTPUT)


if __name__ == '__main__':
    main()
