#!/usr/bin/env python3
"""Build the dated visual handoff for structural depth navigation."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'depth-breadcrumb-navigation-2026-09-04.html'

OUT.write_text('''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Depth breadcrumbs + history — SystemSketch</title>
<style>
  :root{color-scheme:dark;--bg:#10141a;--card:#18202a;--line:#2b3848;--ink:#e8f0f7;--muted:#a6b7c7;--blue:#66aaff;--green:#67d98a;--amber:#ffac4d}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 18% 0,#1b2d43,transparent 40%),var(--bg);color:var(--ink);font:16px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}.wrap{max-width:1180px;margin:auto;padding:52px 26px 80px}h1{max-width:900px;font-size:clamp(2rem,5vw,4rem);line-height:1.04;margin:0 0 16px}h2{margin:44px 0 12px;font-size:1.4rem}.lead{max-width:780px;color:var(--muted);font-size:1.12rem}.chips{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.chip{border:1px solid var(--line);border-radius:99px;padding:4px 10px;color:var(--muted);font-size:.82rem}.card{background:color-mix(in srgb,var(--card) 92%,transparent);border:1px solid var(--line);border-radius:18px;padding:22px;margin:16px 0}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}.axis{font-size:1.1rem;font-weight:760}.axis b{display:block;color:var(--blue);font-size:.78rem;letter-spacing:.08em;text-transform:uppercase}.flow{display:flex;gap:10px;align-items:center;flex-wrap:wrap;font-weight:700}.node{border:1px solid var(--line);border-radius:9px;padding:7px 10px;background:#111923}.arrow{color:var(--blue)}img{display:block;width:100%;border-radius:14px;border:1px solid var(--line);background:#fff}figcaption{color:var(--muted);font-size:.9rem;margin:8px 2px}.proof{border-left:3px solid var(--green);padding-left:15px}.links a{color:#94c5ff}.small{color:var(--muted);font-size:.9rem}@media(max-width:760px){.split{grid-template-columns:1fr}.wrap{padding:34px 16px 60px}}
</style></head><body><main class="wrap">
<p class="small">SystemSketch implementation gallery · 2026-09-04</p>
<h1>Breadcrumbs describe structure. Back/Forward describe where you were.</h1>
<p class="lead">Depth isolation keeps its Step In and structural Up behavior. The old compressed “Depth Stack” surface is now an inline path: root and current scope remain visible, while the full ancestor path stays one click away.</p>
<div class="chips"><span class="chip">session-only</span><span class="chip">not serialized</span><span class="chip">not undo history</span><span class="chip">one shared navigation transaction</span></div>
<section class="split"><article class="card axis"><b>Structural axis</b>Up and crumbs move through real containment ancestry.<div class="flow"><span class="node">Board</span><span class="arrow">›</span><span class="node">System</span><span class="arrow">›</span><span class="node">Scheduler</span></div></article><article class="card axis"><b>Chronological axis</b>Back and Forward restore prior session locations, including camera and safe selection.<div class="flow"><span class="node">previous view</span><span class="arrow">← →</span><span class="node">current view</span></div></article></section>
<section class="card"><h2>What shipped</h2><ul><li>Inline Board → current-scope breadcrumb, structural Up, and a selectable full-path popover.</li><li>Independent session-local Back/Forward history; a new route after Back clears Forward.</li><li>Stale/deleted locations are skipped rather than crashing or reviving invalid scope.</li><li>Board Overview landmarks route through this same transaction, so a target outside an isolated block becomes visible and creates exactly one history hop.</li></ul></section>
<section><h2>Real browser evidence</h2><figure><img src="assets/depth-breadcrumb-navigation-2026-09-04.png" alt="SystemSketch showing the Breadcrumb path popover over a nested Dispatch block"><figcaption>Real-browser CDP journey: three nested Expanded Blocks, Back → Forward → structural Up, then the full path popover. Screenshot inspected after the run.</figcaption></figure></section>
<section><h2>Human review fixture</h2><figure><img src="../sketches/review/depth-breadcrumb-navigation.png" alt="Guided SystemSketch review board with nested System, Scheduler, and Dispatch blocks"><figcaption>Fixture has real nested Block parentage, numbered orange cues, and a green visible pass condition. It was generated through the live editor, cold-reopened, visually inspected, then driven once in the real app.</figcaption></figure><p class="proof"><strong>Verified:</strong> TypeScript build, 115 Vitest files / 1151 tests, 115 Python tests, and the real-browser breadcrumb journey all passed.</p></section>
<section class="card links"><h2>Review</h2><p><a href="../sketches/review/depth-breadcrumb-navigation.systemsketch">Open the review board</a> · <a href="depth-breadcrumb-navigation-review.recipe.json">Read the fixture recipe</a> · <a href="../tests/depth_breadcrumb_navigation_smoke.mjs">Read the CDP journey</a></p><p class="small">Known limitation: this is a session-local navigation trail. Reloading intentionally begins a new trail; it does not become board data or participate in tldraw undo.</p></section>
</main></body></html>\n''', encoding='utf-8')
print(OUT)
